# Generated by Django 3.0.3 on 2020-09-22 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operating_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(blank=True, max_length=30)),
                ('IP_address', models.CharField(max_length=30)),
                ('MAC_address', models.CharField(max_length=30)),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date (mm/dd/yyyy)')),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('operating_system', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoapp.Operating_system')),
            ],
        ),
    ]
